#!/usr/bin/env python3
"""Turn recordings in audio/raw/ into trimmed, normalised audio/<key>.m4a + manifest.

Usage:  python3 tools/build_audio.py [--force]
Needs:  ffmpeg
"""

import array
import json
import math
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "audio" / "raw"
OUT = ROOT / "audio"
SRC_EXT = {".webm", ".mp4", ".m4a", ".wav", ".aiff", ".aif", ".mp3", ".ogg", ".caf"}

# Loudness only — the trim is done by find_bounds(), not by silenceremove.
# A fixed -40dB gate cut the [ç] of ひゃ/ひゅ/ひょ and the [ɸ] of ふ: those
# consonants sit 30dB under the vowel, so a fixed gate starts at the vowel and
# the kana loses its consonant entirely.
# alimiter needs level=disabled, or it auto-levels the result back up to full scale.
FILTER = (
    "loudnorm=I=-16:TP=-2.0:LRA=11,"
    "alimiter=limit=0.85:level=disabled"
)

FRAME_MS = 10
PAD_HEAD = 0.07   # keep this much before the first sound: breathy onsets live here
PAD_TAIL = 0.08


def envelope(path, sr=8000):
    """Per-frame peak level in dBFS."""
    r = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(path), "-f", "s16le", "-ac", "1", "-ar", str(sr), "-"],
        capture_output=True)
    a = array.array("h")
    a.frombytes(r.stdout)
    n = int(sr * FRAME_MS / 1000)
    env = []
    for i in range(0, len(a) - n, n):
        peak = max(abs(x) for x in a[i:i + n]) or 1
        env.append(20 * math.log10(peak / 32768))
    return env


def find_bounds(path):
    """(start, end) seconds. Thresholds follow each file's own noise floor."""
    env = envelope(path)
    if not env:
        return None
    peak = max(env)
    floor = sorted(env)[len(env) // 5]          # 20th percentile ≈ room tone
    core = [i for i, v in enumerate(env) if v > peak - 12]
    if not core:
        return None
    # walk outwards from the loud core while anything is still above the room tone
    gate = max(floor + 6.0, peak - 42.0)
    s = core[0]
    while s > 0 and env[s - 1] > gate:
        s -= 1
    e = core[-1]
    while e < len(env) - 1 and env[e + 1] > gate:
        e += 1
    start = max(0.0, s * FRAME_MS / 1000 - PAD_HEAD)
    end = (e + 1) * FRAME_MS / 1000 + PAD_TAIL
    return start, end


def duration(path):
    """Seconds, via ffprobe when present, otherwise parsed from ffmpeg's own output."""
    try:
        r = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "default=nw=1:nk=1", str(path)],
            capture_output=True, text=True)
        return float(r.stdout.strip())
    except (FileNotFoundError, ValueError):
        pass
    r = subprocess.run(["ffmpeg", "-i", str(path)], capture_output=True, text=True)
    m = re.search(r"Duration: (\d+):(\d+):([\d.]+)", r.stderr)
    if not m:
        return 0.0
    h, mi, s = m.groups()
    return int(h) * 3600 + int(mi) * 60 + float(s)


def main():
    force = "--force" in sys.argv
    if not RAW.exists():
        print("no audio/raw/ yet — record first with tools/record.html", file=sys.stderr)
        RAW.mkdir(parents=True, exist_ok=True)

    sources = sorted(p for p in RAW.iterdir() if p.suffix.lower() in SRC_EXT)
    built, skipped, failed, short = 0, 0, [], []

    for src in sources:
        key = src.stem
        dst = OUT / (key + ".m4a")
        if dst.exists() and not force and dst.stat().st_mtime >= src.stat().st_mtime:
            skipped += 1
            continue
        bounds = find_bounds(src)
        cut = []
        if bounds:
            cut = ["-ss", "%.3f" % bounds[0], "-to", "%.3f" % bounds[1]]
        r = subprocess.run(
            ["ffmpeg", "-y", "-i", str(src)] + cut + ["-af", FILTER,
             "-ac", "1", "-ar", "44100", "-c:a", "aac", "-b:a", "96k", str(dst)],
            capture_output=True, text=True)
        if r.returncode != 0 or not dst.exists():
            failed.append(src.name)
            continue
        d = duration(dst)
        if d < 0.15 or d > 3.0:
            short.append("%s (%.2fs)" % (src.name, d))
        built += 1

    manifest = {}
    for f in sorted(OUT.glob("*.m4a")):
        manifest[f.stem] = round(duration(f), 2)
    (OUT / "manifest.js").write_text(
        "/* generated by tools/build_audio.py — key: unicode codepoints, value: seconds */\n"
        "window.KANA_AUDIO=%s;\n" % json.dumps(manifest, ensure_ascii=False, sort_keys=True),
        encoding="utf-8")

    print("built %d, skipped %d, total in manifest %d" % (built, skipped, len(manifest)))
    if short:
        print("CHECK THESE (unusual length):\n  " + "\n  ".join(short))
    if failed:
        print("FAILED:\n  " + "\n  ".join(failed), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
